### ISSUE TITLE
zonemaster-engine modules don't seem to have meta info for RPM

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster#461] opened 2016-05-11 12:18 UTC
I've just built zonemaster-engine 1.0.13 on a CentOS 7 box, using a SPEC file I created. It's a very basic spec file, so it's nowhere near usable, yet. However, I've run into some RPM-related issues.

First, I'll tell you how I am building it. In my spec file, I have many, many perl modules listed in the "BuildRequires" section. These are all available in CentOS base or EPEL. I had to painstakingly chase each dependency from a manual build process. Now, there are still some modules needed by Zonemaster, that aren't in any CentOS repos. So these get installed by using cpanm. I call cpanm like this:

```
%install
cpanm -l %{buildroot}/opt/zonemaster %{SOURCE0}
```

This makes RPM install zonemaster-engine using cpanm, and cpanm resolves the missing dependencies and installs them. This then results in a zonemaster-engine RPM, that if deployed to a CentOS 7 box, will place zonemaster into /opt, away from the rest of the system, and not pollute /usr/bin with anything that is not from RPM. This is a very important feature of an RPM system - we should not litter /usr/bin and /usr/lib with things that aren't from RPM packages.

However, yum fails to install this RPM, with these errors:

```
--> Finished Dependency Resolution
Error: Package: zonemaster-engine-1.0.13-1.el7.gii.x86_64 (/zonemaster-engine-1.0.13-1.el7.gii.x86_64)
           Requires: perl(Zonemaster)
```

This error is repeated for several submodules, such as Zonemaster::ASNLookup, or Zonemaster::Nameserver, and so on.

The thing is, these modules _are_ present in the package, but RPM's perl dependency resolver didn't see them, where it sees them for other perl modules installed from RPM. For example, if I do:

```
rpm -qp --provides /path/to/zonemaster.rpm
perl(App::Prove) = 3.36
perl(App::Prove::State) = 3.36
perl(App::Prove::State::Result) = 3.36
perl(App::Prove::State::Result::Test) = 3.36
perl(B::Hooks::EndOfScope) = 0.20
perl(B::Hooks::EndOfScope::PP) = 0.20
perl(B::Hooks::EndOfScope::XS) = 0.20
perl(CPAN::Meta) = 2.150005
...
...
```

Note that these modules were installed as dependencies of zonemaster, and RPM recognises them, and adds them to the "provides" metadata of the RPM. But not zonemaster itself.

Here's what happens. When RPM builds a package, it calls /usr/lib/rpm/perl.prov at the end. So, for example:

```
/usr/lib/rpm/perl.prov /var/lib/mock/centos-7-x86_64/root/builddir/build/BUILDROOT/zonemaster-engine-1.0.13-1.el7.gii.x86_64/opt/zonemaster/lib/perl5/App/Prove.pm 
perl(App::Prove) = 3.36
```

However, none of the zonemaster modules return this information:

```
/usr/lib/rpm/perl.prov /var/lib/mock/centos-7-x86_64/root/builddir/build/BUILDROOT/zonemaster-engine-1.0.13-1.el7.gii.x86_64/opt/zonemaster/lib/perl5/Zonemaster.pm
```

So something is missing in the zonemaster perl modules, but I don't know what. I'm not a perl expert, so I can't figure it out.

**Comment by aabdnn** [comment] 2016-05-11 12:26
Actually, I think I have found the problem. The script /usr/lib/rpm/perl.prov expects version numbers, if present in a perl module, to be a number, eg. 1.1.1.

However, zonemaster modules all declare the version like this:

```
package Zonemaster::Nameserver v1.1.1;
```

I think the "v" in front of the version number is wrong.

**Comment by pawal** [comment] 2016-05-11 12:34
Yes, it seems that version numbers should be fixed.

http://perldoc.perl.org/perlmodstyle.html#Version-numbering

**Comment by aabdnn** [comment] 2016-05-11 14:01
I can confirm that "package <name> <version>" does not work at all with rpm's perl provides script.

What you need instead at the top of every module is:

```
package Zonemaster;
our $VERSION ='1.1.1';
```

Note that the version number isn't strictly necessary, especially as you're not enforcing use of specific versions with "use". You may just want to remove the version numbers from all modules except the top-level Zonemaster.pm module.

**Comment by sandoche2k** [comment] 2016-05-11 14:05
It seems that we do not have this issue for debian. Anyway, we are looking
into this issue and get back to you ASAP.

**Comment by aabdnn** [comment] 2016-05-11 14:08
Well, I did start by saying that this is specific to RPM, and so probably won't affect .deb packages. Debian's way of versioning may be more loose, or they don't care.

**Comment by aabdnn** [comment] 2016-05-13 07:56
I've spent the whole day on figuring out how best to package Zonemaster for CentOS 7. I've also managed to figure out how to make rpm ignore the provides/requires dependencies for it. This is achieved by including the following 2 directives in the spec file:

```
%global __provides_exclude_from /opt/zonemaster
%global __requires_exclude_from /opt/zonemaster
```

This makes rpm skip the provides/requires processing altogether. This may not be the best solution for a general public-release RPM into the EPEL repository, for example, but for our personal use, it is just fine. This also allows the entire zonemaster package to be self-contained in /opt/zonemaster without affecting the base system in any way.

**Comment by sandoche2k** [comment] 2016-05-13 08:28
Anand.. thanks for your efforts. 

I will discuss with @vlevigneron  and @pawal before confirming the best option

**Comment by letoams** [comment] 2016-06-27 12:05
the only package I found missing on fedora is perl-Net-IP-XS, which i'll submit to fedora.

My next issue on packaging on fedora was the perl-ldns version. We have the perl package as created by ldns. It seems to live in DNS/LDNS while zonemaster seems to want it in NET/LDNS. Running a patch to fix these references, I end up with another ldns related error:

```
+ make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ............ 1/? Bailout called.  Further testing stopped:  

#   Failed test 'use Zonemaster;'
#   at t/00-load.t line 9.
#     Tried to use 'Zonemaster'.
#     Error:  Can't load '/usr/lib64/perl5/vendor_perl/auto/DNS/LDNS/LDNS.so' for module DNS::LDNS: /usr/lib64/perl5/vendor_perl/auto/DNS/LDNS/LDNS.so: undefined symbol: ldns_rbtree_null_node at /usr/share/perl5/XSLoader.pm line 70, <DATA> line 1.
#  at /usr/lib64/perl5/vendor_perl/DNS/LDNS.pm line 680.

```

**Comment by letoams** [comment] 2016-06-27 12:06
I put up my srpm at: ftp://ftp.nohats.ca/perl-Zonemaster-1.0.14-1.fc24.src.rpm

**Comment by letoams** [comment] 2016-06-27 12:08
oh and ftp://ftp.nohats.ca/perl-Net-IP-XS-0.17-1.fc24.src.rpm

**Comment by jtalir** [comment] 2016-09-06 16:24
I've got a little bit further. 

Looks like 'undefined symbol:' is caused by broken perl-ldns package on Fedora (at least F23 and F24).  LDNS.so from package is not linked with libldns.so
```
$ ld /usr/lib64/perl5/vendor_perl/auto/DNS/LDNS/LDNS.so 2>&1 | grep 'undefined reference' | wc -l
377
$ ldd /usr/lib64/perl5/vendor_perl/auto/DNS/LDNS/LDNS.so
	linux-vdso.so.1 (0x00007ffe04f45000)
	libperl.so.5.22 => /lib64/libperl.so.5.22 (0x00007f6005d3c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f600597a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f600575d000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f6005543000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f600532a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6005125000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6004e1c000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f6004be6000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f60049e2000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559b63fda000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f60047df000)
```
When I built it again from srpm - https://dl.fedoraproject.org/pub/fedora/linux/updates/23/SRPMS/l/ldns-1.6.17-18.fc23.src.rpm I got working version

Next issue with specfile was missing build dependency on perl-Test-Fatal, this one was easily resolved.

Unfortunately looks like ldns in Fedora - ldns-1.6.17-18 - contains some old version of perl binding that is not compatible with Zonemaster. Tests fail on
```
Can't locate object method "new_from_wireformat" via package "DNS::LDNS::Packet" at /home/jara/rpmbuild/BUILD/Zonemaster-v1.0.14/blib/lib/Zonemaster/Nameserver.pm line 378, <$fh> line 6
```
new_from_wireformat method is not in this version.

**Comment by mtoma** [comment] 2016-09-26 09:32
Hello Anand and Jaromir,

It seems to me that both of you are trying to package the zonemaster-engine package with a wrong dependency.

In the error messages I see DNS::LDNS. This is a perl wrapper for the LDNS C library provided by NLnetlabs.

This is NOT the module the zonemaster project requires.
There are two LDNS modules on CPAN DNS::LDNS and Net::LDNS.
The required LDNS perl module is here:
http://search.cpan.org/~cdybed/Net-LDNS-0.75/lib/Net/LDNS.pm

Zonemaster depends ONLY on Net::LDNS. This module has all the net-ldns C code embedded and doesn't not have any dependency on the external ldns.so module as all the code is self contained and compiled with the perl module.

**Comment by jtalir** [comment] 2016-09-27 22:22
Hi Michal,
you are right. I just thought that perl library contained in Fedora ldns package is older version of required library. Looks like it isn't. So I started from scratch and created package also for Net::LDNS. All packages are available in my copr repository https://copr.fedorainfracloud.org/coprs/jtalir/zonemaster/ . Any Fedora (F23, F24, F25) user can easily install zonemaster-cli by these commands:
```
     dnf copr enable jtalir/zonemaster
     dnf install perl-Zonemaster-CLI
```
It would be nice if backend and gui could have Makefile.PL that install everything, not just perl library but also docs and web application

**Comment by mtoma** [comment] 2016-12-13 09:43
Seems the "v" in front of the version is not the real issue.
It seems the perl modules need to use the our $VERSION = x.x.x syntax to be understoond by the /usr/lib/rpm/perl.prov script.

This 

```
package Zonemaster v1.0.16;
```

syntax is not understood by perl.prov

but  this one:
```
package Zonemaster;

our $VERSION =  v1.0.16;
```

is.

**Comment by mtoma** [comment] 2016-12-13 09:58
But after all the "v" seems to be an issue as this
```
package Zonemaster;

our $VERSION =  'v1.0.16';
```

Doesn't work with the perl.prov script.

**Comment by aabdnn** [comment] 2016-12-13 10:02
I still think that there is absolutely no need to have a "v" in front of the version number. Just drop it, and make all version numbers just numbers, like "1.0.16". What purpose does the "v" serve?

**Comment by vlevigneron** [comment] 2016-12-17 10:37
@aabdnn  I just read again PBP about Versions numbers. The advice is to use version CPAN module. That's what I did to test with perl.prov. We use dotted-decimal $VERSION in Zonemaster so according to http://search.cpan.org/~jpeacock/version-0.9917/lib/version.pod here is the syntax that should be used:

`use version; our $VERSION = version->declare("v1.2.3");` 

And is it the result of perl.prov:

```
[...]
# use version; our $VERSION = version->declare("v1.2.3");
# VERSION 1.002.003 at /usr/local/share/perl5/Zonemaster.pm line 4
perl(Zonemaster.pm) = 1.002.003
```

Is it OK for you ?

**Comment by jtalir** [comment] 2016-12-19 11:19
I just tested this:
```
package Zonemaster;
our $VERSION = version->declare("v1.0.14");
```
and it works well. RPM built on Centos 7 correctly includes Provides "perl(Zonemaster) = 1.0.14". The same must be done for all .pm files in all projects.

**Comment by sandoche2k** [comment] 2017-02-09 10:42
@mtoma Please update the .pm files for backend and the GUI

**Comment by sandoche2k** [comment] 2017-04-20 07:59
@mtoma Can you update the .pm files for the backend and the GUI so that we can close this issue

**Comment by mtoma** [comment] 2017-05-29 12:23
The backend and gui do both have the working versionning scheme like this:

package SomePackage;
our $VERSION =  '1.0.16';

(Without the v in front of the versions).

I think this issue can be now closed.

**Comment by matsduf** [comment] 2017-05-29 12:25
The version scheme works for packaging. We close this.

**Closed by matsduf** 2017-05-29 12:25 UTC
Labels: bug, Prio High, test code

**Comment by pawal** [comment] 2017-05-29 12:29
The version scheme in the engine still prepends a 'v' to the version, should it not also be fixed in order to be consistent?

**Comment by vlevigneron** [comment] 2017-05-29 12:42
In Engine, we use format like:

use version; our $VERSION = version->declare("v1.1.0");

which seems to be "one" way (we all know Perl mantra) versions should be
declared. And it works also. And this is this last point that it is the
most important. If there is only one way in GUI files, only one way in
Engine files, ... and if they all work, that's fine.

2017-05-29 14:29 GMT+02:00 Patrik Wallström <notifications@github.com>:

**Comment by jonasbn** [comment] 2017-05-31 11:47
I don't of this would be of interest or useful in your situation, but I have implemented a Perl::Critic policy to help in keeping version numbers consistent using a policy.

Ref: https://metacpan.org/release/Perl-Critic-Policy-logicLAB-RequireVersionFormat
