### ISSUE TITLE
Support for uppercase/lowercase queries (0x20) 

### ISSUE THREAD

**Issue by pettai** [dotse/zonemaster#372] opened 2015-04-28 12:08 UTC
Hi,

It would be useful if zonemaster supported 0x20 queries (uppercase/lowercase mixed zone names)
We're still seeing some problem domains/nameservers that aren't RFC complaint in that partical case...
First that comes to mind is LinkedIn's CDN provider(s): static.licdn.com

Re,
/P

**Comment by pawal** [comment] 2015-04-29 12:37
Added this in requirements. This is a duplicate of #313, will close #313 now.

A reference for this test case is in section 7.1, RFC 1035.

**Comment by sandoche2k** [comment] 2015-05-17 14:03
@pawal move it to 2015.3.

**Comment by sandoche2k** [comment] 2015-06-04 06:47
@pawal i tested various combinations below:  
   
   www.ietf.org
   WWW.IETF.ORG
   WwW.iEtF.oRg
   wWw.IeTf.OrG

It seems working with the zonemaster-cli. Thanks for clarifying what is still to be done?

**Comment by pawal** [comment] 2015-06-04 07:36
A test should be implemented to check for explicit protocol compliance. Yes, this works since this is how DNS works. But we don't have a test case for it.

**Comment by sandoche2k** [comment] 2015-06-04 07:40
Ok i will write one

**Comment by sandoche2k** [comment] 2015-06-09 09:17
@vlevigneron test spec written -nameserver08.md

**Comment by sandoche2k** [comment] 2015-06-29 08:16
@vlevigneron We did discuss during the F2F. I think this issue has been implemented. Can you verify and close?

**Comment by sandoche2k** [comment] 2015-06-30 13:25
@vlevigneron - normally u have full access rights now. Can you verify and close?

**Closed** 2015-06-30 14:12 UTC
Labels: enhancement, Prio High, test spec

**Comment by vlevigneron** [comment] 2015-06-30 14:20
I was able to merge. Verified and closed...
