### ISSUE TITLE
sollefta.se and ornskoldsvik.se

### ISSUE THREAD

**Issue by tobbe-eklov** [dotse/zonemaster#469] opened 2016-09-01 17:48 UTC
Whats wrong with the test of solleftea.se and ornskoldsvik.se?
Broken DNS yes, but it takes to long time so resolve it.

https://zonemaster.se/test/0388c766f83563e9
https://zonemaster.se/test/a4d1f0af7e181ecd
http://dnscheck.iis.se/?time=1472751850&id=5798158&view=basic&test=standard

/T

**Comment by sandoche2k** [comment] 2016-09-30 11:07
@tobbe-eklov Not so much clear what you want from this issue. 

Do you mean, it takes long time for Zonemaster to resolve. I tested "sollefta.se" which is still broken, but the validation by Zonemaster was pretty fast. 

Can you ealborate more on what you want to be solved from this issue.

**Comment by matsduf** [comment] 2016-11-02 14:07
This ticket does not contain enough information to identify what the problem is. We close it.

**Closed by matsduf** 2016-11-02 14:07 UTC
